// <auto-generated />
using System;
using DIRS_Ketering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DIRS_Ketering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("DIRS_Ketering.Models.Jelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jela");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cena = 5500m,
                            Naziv = "Plata suhomesnatih proizvoda",
                            Opis = "Idealno predjelo"
                        },
                        new
                        {
                            Id = 2,
                            Cena = 200m,
                            Naziv = "Brusketi sa lososom",
                            Opis = "Finger food za sve vrste proslava"
                        },
                        new
                        {
                            Id = 3,
                            Cena = 1500m,
                            Naziv = "Cezar salata",
                            Opis = ""
                        },
                        new
                        {
                            Id = 4,
                            Cena = 1200m,
                            Naziv = "Pileci stapici",
                            Opis = "Hrskavi pileci stapici"
                        });
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.com",
                            Ime = "Admin",
                            Lozinka = "admin123",
                            Rola = "Admin"
                        });
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Porudzbina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VremeKreiranja")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Porudzbine");
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Stavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JeloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kolicina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PorudzbinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PorudzbineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TrenutnaCena")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JeloId");

                    b.HasIndex("PorudzbinaId");

                    b.ToTable("Stavke");
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Porudzbina", b =>
                {
                    b.HasOne("DIRS_Ketering.Models.Korisnik", "Korisnik")
                        .WithMany("Porudzbine")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Stavka", b =>
                {
                    b.HasOne("DIRS_Ketering.Models.Jelo", "Jelo")
                        .WithMany("Stavke")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DIRS_Ketering.Models.Porudzbina", "Porudzbina")
                        .WithMany("Stavke")
                        .HasForeignKey("PorudzbinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");

                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Jelo", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Korisnik", b =>
                {
                    b.Navigation("Porudzbine");
                });

            modelBuilder.Entity("DIRS_Ketering.Models.Porudzbina", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
